In [2]:
!pip3 install sklearn

  Using cached https://files.pythonhosted.org/packages/a0/c5/d2238762d780dde84a20b8c761f563fe882b88c5a5fb03c056547c442a19/scikit_learn-0.21.3-cp36-cp36m-manylinux1_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/cd/c1/50a758e8247561e58cb87305b1e90b171b8c767b15b12a1734001f41d356/joblib-0.13.2-py2.py3-none-any.whl
    100% |████████████████████████████████| 25.2MB 74kB/s eta 0:00:01
  Using cached https://files.pythonhosted.org/packages/19/b9/bda9781f0a74b90ebd2e046fde1196182900bd4a8e1ea503d3ffebc50e7c/numpy-1.17.0-cp36-cp36m-manylinux1_x86_64.whl


In [3]:
from sklearn.decomposition import TruncatedSVD
from sklearn.random_projection import sparse_random_matrix
X = sparse_random_matrix(100, 100, density=0.01, random_state=42)

In [4]:
svd = TruncatedSVD(n_components=5, n_iter=7, random_state=42)
svd.fit(X)

TruncatedSVD(algorithm='randomized', n_components=5, n_iter=7, random_state=42,
             tol=0.0)

In [3]:
print( svd.explained_variance_ratio_ )  
print( svd.explained_variance_ratio_.sum() )  
print( svd.singular_values_ )  

[0.06063696 0.05842599 0.04970872 0.04344233 0.03723615]
0.24945013828489518
[2.58418571 2.52453902 2.32011672 2.17531753 2.04439905]


In [2]:
import numpy as np

In [3]:
N = 3
x = [ [1 , 7 , 10, 5 ],
      [7 , 2 , 3 , 50],
      [10, 3 , 3 , 5 ],
      [5 , 50, 5 , 5 ] ]

In [23]:
x = [[3.4638197, 0], [0, 3.1625874]]

In [24]:
np.linalg.inv(x)

array([[0.28869863, 0.        ],
       [0.        , 0.3161968 ]])

In [17]:
A = np.array([
    [3,1,1],
    [-1,3,1]
])

temp = A.dot(A.T)
S,U = np.linalg.eig(temp)
S_ = np.diag(np.sqrt(S))
V = A.T.dot(U).dot(np.linalg.inv(S_))
print(S)
print(U)
print(V)

[12. 10.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[ 0.40824829 -0.89442719]
 [ 0.81649658  0.4472136 ]
 [ 0.40824829  0.        ]]


In [15]:
np.sqrt(S)

array([3.46410162, 3.16227766])

In [9]:
U

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [10]:
V

array([[ 0.40824829, -0.89442719],
       [ 0.81649658,  0.4472136 ],
       [ 0.40824829,  0.        ]])